spring.application.name=expense-tracker
spring.config.import=optional:file:.env[.properties]
server.port=9090
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/expense_tracker}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin@123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

server.servlet.context-path=/api

app.security.jwt.secret=${JWT_SECRET:EI2+V47EL+2C2x3ANCPn0OKGmhL8Z4OzFRZas7FAmd65SvQhgeai0x/mpKlCe7ngfcu7FNVI8r9sJjPWO5KKcg==}
app.security.jwt.expiration=86400000
app.seed.enabled=${APP_SEED_ENABLED:true}
app.budget.alert.thresholds=80,90,100
app.recurring.generation.cron=${APP_RECURRING_GENERATION_CRON:0 0 1 * * *}
app.email.reports.enabled=${APP_EMAIL_REPORTS_ENABLED:true}
app.email.reports.cron=${APP_EMAIL_REPORTS_CRON:0 0 9 1 * *}
app.email.reports.from=${APP_EMAIL_REPORTS_FROM:no-reply@expensetracker.local}
