package com.expensetracker.observability;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.DistributionSummary;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import java.util.concurrent.TimeUnit;
import org.springframework.stereotype.Service;

@Service
public class ObservabilityMetricsService {

    private final MeterRegistry meterRegistry;

    public ObservabilityMetricsService(MeterRegistry meterRegistry) {
        this.meterRegistry = meterRegistry;
    }

    public void recordAuthRequest(String operation, String outcome, long durationNanos) {
        Timer.builder("expense_tracker.auth.requests")
                .description("Authentication request duration")
                .tag("operation", operation)
                .tag("outcome", outcome)
                .register(meterRegistry)
                .record(durationNanos, TimeUnit.NANOSECONDS);
    }

    public void incrementExportJobCreated(String type) {
        Counter.builder("expense_tracker.exports.jobs.created")
                .description("Export jobs created")
                .tag("type", type)
                .register(meterRegistry)
                .increment();
    }

    public void recordExportJobProcessed(String type, String outcome, long durationNanos, int fileSizeBytes) {
        Timer.builder("expense_tracker.exports.jobs.processed")
                .description("Export job processing duration")
                .tag("type", type)
                .tag("outcome", outcome)
                .register(meterRegistry)
                .record(durationNanos, TimeUnit.NANOSECONDS);

        if (fileSizeBytes >= 0) {
            DistributionSummary.builder("expense_tracker.exports.file.size.bytes")
                    .description("Generated export file size in bytes")
                    .tag("type", type)
                    .register(meterRegistry)
                    .record(fileSizeBytes);
        }
    }

    public void recordRecurringRun(String trigger, int processedRules, int generatedExpenses, long durationNanos) {
        Timer.builder("expense_tracker.recurring.runs")
                .description("Recurring expense generation duration")
                .tag("trigger", trigger)
                .register(meterRegistry)
                .record(durationNanos, TimeUnit.NANOSECONDS);

        DistributionSummary.builder("expense_tracker.recurring.rules.processed")
                .description("Recurring rules processed per run")
                .tag("trigger", trigger)
                .register(meterRegistry)
                .record(processedRules);

        DistributionSummary.builder("expense_tracker.recurring.expenses.generated")
                .description("Expenses generated by recurring runs")
                .tag("trigger", trigger)
                .register(meterRegistry)
                .record(generatedExpenses);
    }

    public void recordEmailSend(String trigger, String outcome, long durationNanos) {
        Timer.builder("expense_tracker.email.sends")
                .description("Email report send duration")
                .tag("trigger", trigger)
                .tag("outcome", outcome)
                .register(meterRegistry)
                .record(durationNanos, TimeUnit.NANOSECONDS);
    }
}
